server:
  port: 8082

spring:
  application:
    name: notification-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 3s
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-consumer-group

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

app:
  kafka:
    partitions: 3
    replication-factor: 1
    consumer-concurrency: 3
    topics:
      order-created: order.created.v1
      order-created-dlq: order.created.v1.dlq
      order-shipped: order.shipped.v1
      order-shipped-dlq: order.shipped.v1.dlq
      product-created: product.created.v1
      product-created-dlq: product.created.v1.dlq
