server:
  port: 8083

spring:
  application:
    name: product-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

app:
  kafka:
    partitions: 3
    replication-factor: 1
    topics:
      product-created: product.created.v1
      product-created-dlq: product.created.v1.dlq

logging:
  file:
    name: ${LOG_FILE_PATH:/var/log/app/application.log}
